release-date = "2024-01-07"

[[entries]]
id = "216daa3f-fc5e-487d-989e-6dba8e92ccf7"
type = "feature"
description = "Add sqlx database create and drop tasks"
author = "nicolas.vizzari@helsing.ai"

[[entries]]
id = "03c2043b-e016-400c-900a-6f0844877de0"
type = "improvement"
description = "`Currentable.as_current()` now returns self"
author = "@NiklasRosenstein"

[[entries]]
id = "c778f849-7552-4bde-ace4-34190fa84c8d"
type = "feature"
description = "Add `pytest(include_dirs)` to add additional directories for testing"
author = "@NiklasRosenstein"
