release-date = "2023-06-13"

[[entries]]
id = "394465ea-19e4-4a15-b83a-260df55a5d13"
type = "improvement"
description = "Added colorful error handling"
author = "chris.cunningham@helsing.ai"
pr = "https://github.com/kraken-build/kraken-build/pull/31"
