release-date = "2023-06-08"

[[entries]]
id = "9454562d-7a0b-47c9-9d8d-a00fc2b29123"
type = "improvement"
description = "Make cargo fmt use the nightly toolchain by default"
author = "nicolas.vizzari@helsing.ai"
pr = "https://github.com/kraken-build/kraken-build/pull/34"
