[[entries]]
id = "f0b6da17-e82e-451b-b919-81529b97cd30"
type = "feature"
description = "Add `kraken.build` module which allows importing the current `context` and `project` from a build script as if calling `Context.current()` or `Project.current()`"
author = "@NiklasRosenstein"

[[entries]]
id = "fb71b3bb-5c65-4c3f-a629-a9e87cdd099f"
type = "feature"
description = "Add experimental Target API"
author = "@NiklasRosenstein"
